export const constants = {
    API_URL: 'http://dummy.restapiexample.com/api/v1/employees',
    ADD_EMPLOYEE: 'Add Employee',
    UPDATE_EMPLOYEE: 'Update Employee',
    DELETE_EMPLOYEE: 'Delete Employee',
    EMPLOYEE_ADDED: 'Employee added successfully!!',
    EMPLOYEE_UPDATED: 'Employee updated successfully!!',
    EMPLOYEE_DELETED: 'Employee deleted successfully!!',
    DELETE_MESSAGE: 'Do you want to delete the employee',
    LOADING_EMPLOYEE_MESSAGE: 'Fetching employees details',
    IMAGE_UPLOAD_MESSAGE: 'Image uploaded successfully!!',
    IMAGE_UPLOAD_ERROR: 'Error while selecting image.',
    IMAGE_STORE_ERROR: 'Error while storing file.',
    SELECT_IMAGE_SOURCE: 'Select Image Source',
    LOAD_SOURCE_LIBRARY: 'Load from Library',
    LOAD_SOURCE_CAMERA: 'Use Camera',
    CANCEL_BUTTON: 'Cancel',
    OK_BUTTON: 'OK',
};
